// <auto-generated />
namespace Aurora.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class UserModel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UserModel));
        
        string IMigrationMetadata.Id
        {
            get { return "201307070529422_UserModel"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
