// <auto-generated />
namespace Aurora.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class ProgressionModel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ProgressionModel));
        
        string IMigrationMetadata.Id
        {
            get { return "201307071858427_ProgressionModel"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
