// <auto-generated />
namespace Aurora.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class HiringProcessModel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(HiringProcessModel));
        
        string IMigrationMetadata.Id
        {
            get { return "201307071643409_HiringProcessModel"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
