// <auto-generated />
namespace Aurora.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class InitialPrimitives : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(InitialPrimitives));
        
        string IMigrationMetadata.Id
        {
            get { return "201307031833523_InitialPrimitives"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
